url: 'https://byang12159.github.io/' # your main domain
baseurl: 'personal_portfolio/'
# theme: 'pages-themes/cayman@v0.2.0'
# markdown: GFM

# theme: jekyll-theme-hacker

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one